# Generated by Django 5.1.3 on 2024-11-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=15)),
                ('fruit_type', models.CharField(choices=[('apple', 'Apple'), ('pear', 'Pear')], max_length=10)),
                ('reading_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reading_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capture_date', models.DateTimeField()),
                ('sample_status', models.CharField(choices=[('I', 'I'), ('R', 'R'), ('S', 'S'), ('Z', 'Z')], max_length=1)),
                ('capture_station', models.CharField(max_length=225)),
            ],
        ),
    ]
