# Generated by Django 5.1.3 on 2024-11-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_pressurereading_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressurereading',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='pressurereading',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
